<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="6" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="AppTest" duration-ms="30" started-at="2017-04-28T09:48:35Z" finished-at="2017-04-28T09:48:35Z">
    <groups>
    </groups>
    <test name="AppTest" duration-ms="30" started-at="2017-04-28T09:48:35Z" finished-at="2017-04-28T09:48:35Z">
      <class name="com.cisco.test.jenkinsTest.SampleTest">
        <test-method status="FAIL" signature="failingTest()[pri:0, instance:com.cisco.test.jenkinsTest.SampleTest@2ff4f00f]" name="failingTest" duration-ms="9" started-at="2017-04-28T15:18:35Z" finished-at="2017-04-28T15:18:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.cisco.test.jenkinsTest.SampleTest.failingTest(SampleTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failingTest -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.cisco.test.jenkinsTest.SampleTest@2ff4f00f]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-04-28T15:18:35Z" finished-at="2017-04-28T15:18:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=failingTest status=FAILURE method=SampleTest.failingTest()[pri:0, instance:com.cisco.test.jenkinsTest.SampleTest@2ff4f00f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.cisco.test.jenkinsTest.SampleTest@2ff4f00f]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-04-28T15:18:35Z" finished-at="2017-04-28T15:18:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=failingTest1 status=FAILURE method=SampleTest.failingTest1()[pri:0, instance:com.cisco.test.jenkinsTest.SampleTest@2ff4f00f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="failingTest1()[pri:0, instance:com.cisco.test.jenkinsTest.SampleTest@2ff4f00f]" name="failingTest1" duration-ms="0" started-at="2017-04-28T15:18:35Z" finished-at="2017-04-28T15:18:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.cisco.test.jenkinsTest.SampleTest.failingTest1(SampleTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failingTest1 -->
        <test-method status="FAIL" signature="failingTest2()[pri:0, instance:com.cisco.test.jenkinsTest.SampleTest@2ff4f00f]" name="failingTest2" duration-ms="0" started-at="2017-04-28T15:18:35Z" finished-at="2017-04-28T15:18:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.cisco.test.jenkinsTest.SampleTest.failingTest2(SampleTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failingTest2 -->
        <test-method status="PASS" signature="passingTest()[pri:0, instance:com.cisco.test.jenkinsTest.SampleTest@2ff4f00f]" name="passingTest" duration-ms="0" started-at="2017-04-28T15:18:35Z" finished-at="2017-04-28T15:18:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- passingTest -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.cisco.test.jenkinsTest.SampleTest@2ff4f00f]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-04-28T15:18:35Z" finished-at="2017-04-28T15:18:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=failingTest2 status=FAILURE method=SampleTest.failingTest2()[pri:0, instance:com.cisco.test.jenkinsTest.SampleTest@2ff4f00f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.cisco.test.jenkinsTest.SampleTest@2ff4f00f]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-04-28T15:18:35Z" finished-at="2017-04-28T15:18:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=passingTest status=SUCCESS method=SampleTest.passingTest()[pri:0, instance:com.cisco.test.jenkinsTest.SampleTest@2ff4f00f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="passingTest1()[pri:0, instance:com.cisco.test.jenkinsTest.SampleTest@2ff4f00f]" name="passingTest1" duration-ms="0" started-at="2017-04-28T15:18:35Z" finished-at="2017-04-28T15:18:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- passingTest1 -->
        <test-method status="PASS" signature="passingTest2()[pri:0, instance:com.cisco.test.jenkinsTest.SampleTest@2ff4f00f]" name="passingTest2" duration-ms="1" started-at="2017-04-28T15:18:35Z" finished-at="2017-04-28T15:18:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- passingTest2 -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.cisco.test.jenkinsTest.SampleTest@2ff4f00f]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-04-28T15:18:35Z" finished-at="2017-04-28T15:18:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=passingTest1 status=SUCCESS method=SampleTest.passingTest1()[pri:0, instance:com.cisco.test.jenkinsTest.SampleTest@2ff4f00f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.cisco.test.jenkinsTest.SampleTest@2ff4f00f]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-04-28T15:18:35Z" finished-at="2017-04-28T15:18:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=passingTest2 status=SUCCESS method=SampleTest.passingTest2()[pri:0, instance:com.cisco.test.jenkinsTest.SampleTest@2ff4f00f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.cisco.test.jenkinsTest.SampleTest -->
    </test> <!-- AppTest -->
  </suite> <!-- AppTest -->
</testng-results>
